language: cpp
dist: trusty
sudo: required
os:
  - linux
env:
  - NQQ_VERSION=${TRAVIS_TAG:-${TRAVIS_COMMIT}}
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y qtbase5-dev libqt5webkit5-dev libqt5svg5-dev qttools5-dev-tools libuchardet-dev
script:
  - ./configure PREFIX=/usr && make -j4
  - # Dear upstream, please change this so that the next line installs to ./appdir rather than to ./src/ui/appdir 
  - sudo make INSTALL_ROOT=appdir install ; sudo chown -R $USER ./src/ui/appdir ; find ./src/ui/appdir/
  - mv ./src/ui/appdir/usr/local/* ./src/ui/appdir/usr/ # Dear upstream, please change this so that this is not needed
  - # "./src/ui-tests/ui-tests"
  - wget -c "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage" 
  - chmod a+x linuxdeployqt*.AppImage
  - unset QTDIR; unset QT_PLUGIN_PATH ; unset LD_LIBRARY_PATH
  - ./linuxdeployqt*.AppImage ./src/ui/appdir/usr/share/applications/*.desktop -bundle-non-qt-libs -qmldir=$(readlink -f /opt/qt5*/qml/)
  - ./linuxdeployqt*.AppImage ./src/ui/appdir/usr/share/applications/*.desktop -appimage -qmldir=$(readlink -f /opt/qt5*/qml/)
  - curl --upload-file ./notepadqq*.AppImage https://transfer.sh/notepadqq-git.$(git rev-parse --short HEAD)-x86_64.AppImage
